force-app/main/default/objects/Doctor__c/Doctor__c.object-meta.xml
<CustomObject>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Doctor__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Doctors</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Doctors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Patients__c/Patients__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <label>Patient Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patients__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Profile.Name</field>
            <operation>equals</operation>
            <value>Patients</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AppointmentAuraController.cls
public with sharing class AppointmentAuraController {
    public static String currentProfile;
    
	@AuraEnabled
    public static sObject getCurrentUser() {
        currentProfile = getProfile().Name;
        Boolean hasPermission = FeatureManagement.checkPermission('is_Hospital_Admin');
        
        if(currentProfile == 'Doctors'){
            Doctor__c currentDoc = new Doctor__c();
            currentDoc = [SELECT Id,Name FROM Doctor__c WHERE User__c =: UserInfo.getUserId() Limit 1];
            return currentDoc;
        }else if(currentProfile == 'Patients'){
            Patients__c currentPat = new Patients__c();
            currentPat = [SELECT Id,Name FROM Patients__c WHERE User__c =: UserInfo.getUserId() Limit 1];
            return currentPat;
        }else if(hasPermission) {
            User currentUser = new User();
            currentUser = [SELECT Name FROM User WHERE Id =: UserInfo.getUserId() Limit 1];
            return currentUser;
        } else {
            return null;
        }
    }
    
    
   @AuraEnabled
    public static Profile getProfile(){
      try {
        Profile profile = [SELECT Id, Name FROM Profile WHERE Id =: UserInfo.getProfileId()];
        return profile;
      } catch(Exception e) {
        throw new AuraHandledException(e.getMessage()); 
      }
    }

}